define([],function(){window.Modernizr=function(i,g,m){function o(a,c){return typeof a===c}function q(a,c){for(var f in a)if(h[a[f]]!==m)return"pfx"==c?a[f]:!0;return!1}function k(a,c){var f=a.charAt(0).toUpperCase()+a.substr(1),f=(a+" "+l.join(f+" ")+f).split(" ");return q(f,c)}function E(){d.input=function(a){for(var c=0,f=a.length;c<f;c++)A[a[c]]=!!(a[c]in e);return A}("autocomplete,autofocus,list,placeholder,max,min,multiple,pattern,required,step".split(","));d.inputtypes=function(a){for(var c=
0,f,b,d=a.length;c<d;c++){e.setAttribute("type",b=a[c]);if(f="text"!==e.type)e.value=t,e.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(b)&&e.style.WebkitAppearance!==m?(j.appendChild(e),f=g.defaultView,f=f.getComputedStyle&&"textfield"!==f.getComputedStyle(e,null).WebkitAppearance&&0!==e.offsetHeight,j.removeChild(e)):/^(search|tel)$/.test(b)||(/^(url|email)$/.test(b)?f=e.checkValidity&&!1===e.checkValidity():/^color$/.test(b)?(j.appendChild(e),j.offsetWidth,f=e.value!=t,j.removeChild(e)):
f=e.value!=t);B[a[c]]=!!f}return B}("search,tel,url,email,datetime,date,month,week,time,datetime-local,number,range,color".split(","))}var d={},j=g.documentElement;g.head||g.getElementsByTagName("head");var b=g.createElement("modernizr"),h=b.style,e=g.createElement("input"),t=":)",C=Object.prototype.toString,n=",-webkit-,-moz-,-o-,-ms-,-khtml-".split(","),l=["Webkit","Moz","O","ms","Khtml"],b={},B={},A={},D=[],u,w=function(a,c,f,b){var d,e=g.createElement("div");if(parseInt(f,10))for(;f--;)d=g.createElement("div"),
d.id=b?b[f]:"modernizr"+(f+1),e.appendChild(d);f=["&shy;<style>",a,"</style>"].join("");e.id="modernizr";e.innerHTML+=f;j.appendChild(e);a=c(e,a);e.parentNode.removeChild(e);return!!a},v=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(c,f){var f=f||g.createElement(a[c]||"div"),c="on"+c,b=c in f;b||(f.setAttribute||(f=g.createElement("div")),f.setAttribute&&f.removeAttribute&&(f.setAttribute(c,""),b=o(f[c],"function"),o(f[c],
m)||(f[c]=m),f.removeAttribute(c)));return b}}(),x={}.hasOwnProperty,y;y=!o(x,m)&&!o(x.call,m)?function(a,c){return x.call(a,c)}:function(a,c){return c in a&&o(a.constructor.prototype[c],m)};(function(a,c){var b=a.join(""),e=c.length;w(b,function(a,c){for(var b=g.styleSheets[g.styleSheets.length-1],b=b.cssRules&&b.cssRules[0]?b.cssRules[0].cssText:b.cssText||"",f=a.childNodes,h={};e--;)h[f[e].id]=f[e];d.touch="ontouchstart"in i||9===h.touch.offsetTop;d.csstransforms3d=9===h.csstransforms3d.offsetLeft;
d.generatedcontent=1<=h.generatedcontent.offsetHeight;d.fontface=/src/i.test(b)&&0===b.indexOf(c.split(" ")[0])},e,c)})(['@font-face {font-family:"font";src:url("https://")}',["@media (",n.join("touch-enabled),("),"modernizr){#touch{top:9px;position:absolute}}"].join(""),["@media (",n.join("transform-3d),("),"modernizr){#csstransforms3d{left:9px;position:absolute}}"].join(""),['#generatedcontent:after{content:"',t,'";visibility:hidden}'].join("")],["fontface","touch","csstransforms3d","generatedcontent"]);
b.flexbox=function(){var a=g.createElement("div"),c=g.createElement("div"),b;b="display:";a.style.cssText=(b+n.join("box;"+b)).slice(0,-b.length)+"width:42px;padding:0;";c.style.cssText=n.join("box-flex:1;")+"width:10px;";a.appendChild(c);j.appendChild(a);b=42===c.offsetWidth;a.removeChild(c);j.removeChild(a);return b};b.canvas=function(){var a=g.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))};b.canvastext=function(){return!(!d.canvas||!o(g.createElement("canvas").getContext("2d").fillText,
"function"))};b.webgl=function(){return!!i.WebGLRenderingContext};b.touch=function(){return d.touch};b.geolocation=function(){return!!navigator.geolocation};b.postmessage=function(){return!!i.postMessage};b.websqldatabase=function(){return!!i.openDatabase};b.indexedDB=function(){for(var a=-1,c=l.length;++a<c;)if(i[l[a].toLowerCase()+"IndexedDB"])return!0;return!!i.indexedDB};b.hashchange=function(){return v("hashchange",i)&&(g.documentMode===m||7<g.documentMode)};b.history=function(){return!(!i.history||
!history.pushState)};b.draganddrop=function(){return v("dragstart")&&v("drop")};b.websockets=function(){for(var a=-1,c=l.length;++a<c;)if(i[l[a]+"WebSocket"])return!0;return"WebSocket"in i};b.rgba=function(){h.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+h.backgroundColor).indexOf("rgba")};b.hsla=function(){h.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+h.backgroundColor).indexOf("rgba")||!!~(""+h.backgroundColor).indexOf("hsla")};b.multiplebgs=function(){h.cssText=
"background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(h.background)};b.backgroundsize=function(){return k("backgroundSize")};b.borderimage=function(){return k("borderImage")};b.borderradius=function(){return k("borderRadius")};b.boxshadow=function(){return k("boxShadow")};b.textshadow=function(){return""===g.createElement("div").style.textShadow};b.opacity=function(){var a=n.join("opacity:.55;")+"";h.cssText=a;return/^0.55$/.test(h.opacity)};b.cssanimations=function(){return k("animationName")};
b.csscolumns=function(){return k("columnCount")};b.cssgradients=function(){var a=("background-image:"+n.join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+n.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);h.cssText=a;return!!~(""+h.backgroundImage).indexOf("gradient")};b.cssreflections=function(){return k("boxReflect")};b.csstransforms=function(){return!!q(["transformProperty","WebkitTransform","MozTransform","OTransform","msTransform"])};
b.csstransforms3d=function(){var a=!!q(["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"]);a&&"webkitPerspective"in j.style&&(a=d.csstransforms3d);return a};b.csstransitions=function(){return k("transitionProperty")};b.fontface=function(){return d.fontface};b.generatedcontent=function(){return d.generatedcontent};b.video=function(){var a=g.createElement("video"),c=!1;try{if(c=!!a.canPlayType)c=new Boolean(c),c.ogg=a.canPlayType('video/ogg; codecs="theora"'),
c.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"')||a.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"'),c.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"')}catch(b){}return c};b.audio=function(){var a=g.createElement("audio"),c=!1;try{if(c=!!a.canPlayType)c=new Boolean(c),c.ogg=a.canPlayType('audio/ogg; codecs="vorbis"'),c.mp3=a.canPlayType("audio/mpeg;"),c.wav=a.canPlayType('audio/wav; codecs="1"'),c.m4a=a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")}catch(b){}return c};
b.localstorage=function(){try{return!!localStorage.getItem}catch(a){return!1}};b.sessionstorage=function(){try{return!!sessionStorage.getItem}catch(a){return!1}};b.webworkers=function(){return!!i.Worker};b.applicationcache=function(){return!!i.applicationCache};b.svg=function(){return!!g.createElementNS&&!!g.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};b.inlinesvg=function(){var a=g.createElement("div");a.innerHTML="<svg/>";return"http://www.w3.org/2000/svg"==(a.firstChild&&
a.firstChild.namespaceURI)};b.smil=function(){return!!g.createElementNS&&/SVG/.test(C.call(g.createElementNS("http://www.w3.org/2000/svg","animate")))};b.svgclippaths=function(){return!!g.createElementNS&&/SVG/.test(C.call(g.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var z in b)y(b,z)&&(u=z.toLowerCase(),d[u]=b[z](),D.push((d[u]?"":"no-")+u));d.input||E();d.addTest=function(a,c){if("object"==typeof a)for(var b in a)y(a,b)&&d.addTest(b,a[b]);else{a=a.toLowerCase();if(d[a]!==m)return;
c="boolean"==typeof c?c:!!c();j.className+=" "+(c?"":"no-")+a;d[a]=c}return d};h.cssText="";b=e=null;i.attachEvent&&function(){var a=g.createElement("div");a.innerHTML="<elem></elem>";return 1!==a.childNodes.length}()&&function(a,b){function f(a){for(var b=-1;++b<h;)a.createElement(g[b])}a.iepp=a.iepp||{};var d=a.iepp,e=d.html5elements||"abbr|article|aside|audio|canvas|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",g=e.split("|"),
h=g.length,i=RegExp("(^|\\s)("+e+")","gi"),j=RegExp("<(/*)("+e+")","gi"),k=/^\s*[\{\}]\s*$/,n=RegExp("(^|[^\\n]*?\\s)("+e+")([^\\n]*)({[\\n\\w\\W]*?})","gi"),o=b.createDocumentFragment(),l=b.documentElement,e=l.firstChild,r=b.createElement("body"),s=b.createElement("style"),q=/print|all/,p;d.getCSS=function(a,b){if(a+""===m)return"";for(var c=-1,f=a.length,e,g=[];++c<f;)e=a[c],e.disabled||(b=e.media||b,q.test(b)&&g.push(d.getCSS(e.imports,b),e.cssText),b="all");return g.join("")};d.parseCSS=function(a){for(var b=
[],c;null!=(c=n.exec(a));)b.push(((k.exec(c[1])?"\n":c[1])+c[2]+c[3]).replace(i,"$1.iepp_$2")+c[4]);return b.join("\n")};d.writeHTML=function(){var a=-1;for(p=p||b.body;++a<h;)for(var d=b.getElementsByTagName(g[a]),f=d.length,e=-1;++e<f;)0>d[e].className.indexOf("iepp_")&&(d[e].className+=" iepp_"+g[a]);o.appendChild(p);l.appendChild(r);r.className=p.className;r.id=p.id;r.innerHTML=p.innerHTML.replace(j,"<$1font")};d._beforePrint=function(){s.styleSheet.cssText=d.parseCSS(d.getCSS(b.styleSheets,"all"));
d.writeHTML()};d.restoreHTML=function(){r.innerHTML="";l.removeChild(r);l.appendChild(p)};d._afterPrint=function(){d.restoreHTML();s.styleSheet.cssText=""};f(b);f(o);d.disablePP||(e.insertBefore(s,e.firstChild),s.media="print",s.className="iepp-printshim",a.attachEvent("onbeforeprint",d._beforePrint),a.attachEvent("onafterprint",d._afterPrint))}(i,g);d._version="2.0.6";d._prefixes=n;d._domPrefixes=l;d.mq=function(a){if(i.matchMedia)return matchMedia(a).matches;var b;w("@media "+a+" { #modernizr { position: absolute; } }",
function(a){b="absolute"==(i.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position});return b};d.hasEvent=v;d.testProp=function(a){return q([a])};d.testAllProps=k;d.testStyles=w;d.prefixed=function(a){return k(a,"pfx")};j.className=j.className.replace(/\bno-js\b/,"")+(" js "+D.join(" "));return d}(this,this.document)});
