// Chinese
plupload.addI18n({
    'Select files': '选择文件',
    'Add files to the upload queue and click the start button.': '增加文件至队列并开始上传',
    'Filename': '文件名',
    'Status': '状态',
    'Size': '文件大小',
    'Add Files': '增加文件',
    'Stop Upload': '停止上传',
    'Stop upload': '停止上传',
    'Start Upload': '开始上传',
    'Start upload': '开始上传',
    'Add files': '追加文件',
    'Add files.': '追加文件',
    'Stop current upload': '停止当前的上传',
    'Start uploading queue': '开始上传队列',
    'Uploaded %d/%d files': '上传文件 %d/%d',
    'N/A': '无',
    'Drag files here.': '拖拽文件至此',
    'File extension error.': '文件出现异常',
    'File size error.': '文件尺寸错误',
    'File count error.': '文件数量错误',
    'Init error.': '初始化失败',
    'HTTP Error.': 'HTTP 错误',
    'Security error.': '安全错误',
    'Generic error.': '普通错误',
    'IO error.': 'IO 错误',
    'File: %s': '文件: %s',
    'Close': '关闭',
    '%d files queued': '%d 文件队列',
    'Using runtime: ': '正在执行: ',
    'File: %f, size: %s, max file size: %m': '文件: %f, 大小: %s, 最大允许大小: %m',
    'Upload element accepts only %d file(s) at a time. Extra files were stripped.': '仅允许上传文件 %d 。其余文件被排除',
    'Upload URL might be wrong or doesn\'t exist': '上传地址错误或不存在',
    'Error: File too large: ': '错误: 文件过大: ',
    'Error: Invalid file extension: ': '错误: 不被允许的文件类型: '
});